// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA66M78SHMaO2dNjv44Ju-P5JhpN3eJ6dQ',
    appId: '1:347874070421:web:52f83b6a8d6f5e136e309c',
    messagingSenderId: '347874070421',
    projectId: 'bookingapp-80a1d',
    authDomain: 'bookingapp-80a1d.firebaseapp.com',
    storageBucket: 'bookingapp-80a1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8IKHPZ-ySMF4E62B7toqWEqSYMbtkIE',
    appId: '1:347874070421:android:993e69c2141e59db6e309c',
    messagingSenderId: '347874070421',
    projectId: 'bookingapp-80a1d',
    storageBucket: 'bookingapp-80a1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjbh7yovTLyP5Y5aJE520ZV58JHOyZWo',
    appId: '1:347874070421:ios:3d3ee292c08223756e309c',
    messagingSenderId: '347874070421',
    projectId: 'bookingapp-80a1d',
    storageBucket: 'bookingapp-80a1d.appspot.com',
    androidClientId: '347874070421-abidia9fkj9fq16c4gu05ngo6u9q6ikn.apps.googleusercontent.com',
    iosClientId: '347874070421-417pp77ibc2ark10qlbbr3hu48phs2ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmjbh7yovTLyP5Y5aJE520ZV58JHOyZWo',
    appId: '1:347874070421:ios:3d3ee292c08223756e309c',
    messagingSenderId: '347874070421',
    projectId: 'bookingapp-80a1d',
    storageBucket: 'bookingapp-80a1d.appspot.com',
    androidClientId: '347874070421-abidia9fkj9fq16c4gu05ngo6u9q6ikn.apps.googleusercontent.com',
    iosClientId: '347874070421-417pp77ibc2ark10qlbbr3hu48phs2ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.booking',
  );
}
